spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oajfu7rpj65M2FAh697
            authorization-grant-type: authorization_code
            client-authentication-method: none
            scope:
              - openid
              - profile
              - email
        provider:
          okta:
            issuer-uri: https://demo-azure-marsupial-56101.okta.com/oauth2/ausjfu4hbumYKoFdA697

server:
  forward-headers-strategy: framework
