server:
  port: 8080
  forward-headers-strategy: framework

spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oaw3im3jxwpMB1yD697
            client-secret: a_AiMz4BCiDHqKmEWJt6wlmIeFJX51YKvr2NfpprTaQUUoulb6TzjEURQckquCR4
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/okta"
            scope:
              - openid
              - profile
              - email
        provider:
          okta:
            issuer-uri: https://demo-azure-marsupial-56101.okta.com/oauth2/ausjfu4hbumYKoFdA697

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
